library/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth.views import LogoutView
from django.conf.urls import url
from . import views

app_name = 'library'
urlpatterns = [
  
    path('home', HomeView.as_view(), name='home'),
    path('user-signup', views.signup_user, name="user-signup"),
    path('', views.signin, name="signin"),



    path('logout/', LogoutView.as_view(next_page='library:signin'), name='logout'),

    path('books/', BookView.as_view(), name='book-list'),
    path('book/create/', BookCreate.as_view(), name='book-create'),
    path('book/<slug:pk>/', BookDetail.as_view(), name= 'book'),
    path('book/<slug:pk>/update/', BookUpdate.as_view(), name='book-update'),
    path('book/<slug:pk>/delete/', BookDelete.as_view(), name='book-delete'),



 

]

library_management/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library/models.py
from django.db import models
from django.contrib.auth.models import User
# Used to generate urls by reversing the URL patterns
from django.urls import reverse
from django.db.models.signals import post_save
from django.contrib.auth.models import PermissionsMixin
from django.utils.timezone import now
import uuid
import random
# relation containg all genre of books

from datetime import date, timedelta, datetime
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager







class Genre(models.Model):
    name = models.CharField(
        max_length=200, help_text="Enter a book genre (e.g. Science Fiction, French Poetry etc.)")

    def __str__(self):
        return self.name

class Language(models.Model):
    name = models.CharField(max_length=200,
                            help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)")

    def __str__(self):
        return self.name




class Book(models.Model):
    id = models.UUIDField(primary_key=True, unique=True,
                          default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=100)
    summary = models.TextField(
        max_length=1000, help_text="Enter a brief description of the book")
    isbn = models.CharField('ISBN', max_length=13,
                            help_text='13 Character https://www.isbn-international.org/content/what-isbn')
    genre = models.ManyToManyField(
        Genre, help_text="Select a genre for this book")
    language = models.ForeignKey(
        'Language', on_delete=models.SET_NULL, null=True)
    total_copies = models.IntegerField()
    pic = models.ImageField(blank=True, null=True, upload_to='books')
    available_copies = models.IntegerField(name='available_copies')

    # __str__ method is used to override default string returnd by an object
    def __str__(self):
        return self.title

library/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView, DeleteView, UpdateView, FormView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.urls import reverse_lazy

from django.http import request
from datetime import datetime, timedelta
from django.contrib import messages

from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login


def signin(request):
  
    if request.method=="POST":
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(username=email, password=password)
        if user is not None:
            login(request, user)
            return redirect("library:home")      
        user = authenticate(username=User.objects.get(email=email).username, password=password)  
        if user is not None:
            login(request, user)
            return redirect("library:home")
        else:
            context = {'error':'Invalid Email or Password.'}
            return render(request, 'library/login.html', context)
    return render(request, 'library/login.html')      

def signup_user(request):
 
    if request.method == 'POST':
        email = request.POST['email']
        username = request.POST['username']
        password = request.POST['password']

        try:
            user = User.objects.get(username=username)
            if user:
                return render(request, 'library/register.html', {'error': 'Username Already Exist'})
        except:
            user = None
        
   
        user = User.objects.create_user(email=email, username=username, password=password)
        user.save()
   
        return redirect('library:signin')       
    return render(request, 'library/register.html')



class HomeView(LoginRequiredMixin, TemplateView):
    template_name='library/main.html'
    

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        # context['accounts']=Account.objects.all()
        context['books'] = Book.objects.all()
        search_input=self.request.GET.get('search-area') or ''
        if search_input:
            context['books']=context['books'].filter(
                title__startswith=search_input)

        context['search_input']=search_input
        return context


class BookView(LoginRequiredMixin, ListView):
    model=Book
    context_object_name='books'

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context['books']=context['books']

        search_input=self.request.GET.get('search-area') or ''
        if search_input:
            context['books']=context['books'].filter(
                title__startswith=search_input)

        context['search_input']=search_input

        return context



class BookCreate(LoginRequiredMixin,CreateView):
    model=Book
    permission_required= 'books.add_books'
    fields='__all__'
    success_url=reverse_lazy('library:book-list')


    def form_valid(self, form):
        form.instance.user=self.request.user
        return super(BookCreate, self).form_valid(form)



class BookDetail(LoginRequiredMixin, DetailView):
    model=Book
    context_object_name='book'
    template_name='library/book.html'


    


class BookUpdate(LoginRequiredMixin,UpdateView):
    model=Book
    permission_required = 'books.change_books'
    fields='__all__'
    success_url=reverse_lazy('library:book-list')


class BookDelete(LoginRequiredMixin,DeleteView):
    model=Book
    permission_required = 'books.delete_book'
    context_object_name='book'
    fields='__all__'
    success_url=reverse_lazy('library:book-list')

library/templates/library/base.html
<!doctype html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Library Management System</title>
  </head>
  <style>
    body {
  background-image: url('media/books/books-background-22199819.jpg');
}





    .card-img-top {
    width: 100%;
    height: 15vw;
    object-fit: cover;
    }
    .card{
      margin: 1em auto;
    }
    .about__img {
    margin-top: 1em;
    justify-self: center;
    }
    .profile{
      margin: auto;
      text-align: center;
      font-family: 'Gill Sans', 'Gill Sans MT', 'Calibri', 'Trebuchet MS', sans-serif;
     
    }
    .about__img img {
    width: 300px;
    height: 170px;
    border-radius: .5rem;
    margin-left: 28px;
    margin-right: 20px;
    }
    label {
            padding-top: 10px !important;
            display: block;
        }
    th,td{
      text-align: center;
      margin: auto;
    }
    .flex-container{
      overflow: auto;
    }

    

  </style>
  <body class="container">
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          {% if request.user.is_authenticated %}
          <a class="navbar-brand" href="{% url 'library:home' %}">Books Management</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          {% else %}
          <a class="navbar-brand" href="{% url 'library:signin' %}">Books Management</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          {% endif %}
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'library:home' %}">Home</a>
              </li>


              
            
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Books
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'library:book-list' %}">Books List</a></li>
                  {% if request.user.is_superuser or request.user.is_admin %}
                  <li><a class="dropdown-item" href="{% url 'library:book-create' %}">Add New Book</a></li>
                 {% endif %}
              
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Profile
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  
                  <li><a class="dropdown-item" href="{%url 'library:logout'%}">Logout</a></li>
                 
                </ul>
              </li>
              {% endif %}
            </ul>
            <form  method="GET" class="d-flex">
              <input class="form-control me-2" type="text" placeholder="Search" name="search-area" aria-label="Search" value="{{search_input}}">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
<div class="contaner" style="overflow: auto;">
{% block content %}  {% endblock content %}</div>
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    
  </body>
</html>

library/templates/library/book.html
{% extends 'library/base.html' %}
{% block content %}


<div class="card" style="width: 22rem">
    {% if book.pic %}
    <div class="about__img img">
        <img  src="{{book.pic.url}}" alt="">
    </div>
    {% else %}
    <div class="about__img img">
        <img src="/static/avatar/open-book-clipart-03.png">
    </div>
    {% endif %}
    <br>
    <span style="text-align: center;"><h2>{{book.title|title}}</h2></span>
    <br>
    <p style="width: 50%; margin: auto;"><h4><strong> Summary:</strong> {{book.summary}}</h4></p>
    <p style="width: 50%; margin: auto;"><h4><strong> Genre:</strong> {{book.genre.all|join:', '}}</h4></p>
    <p style="width: 50%; margin: auto;"><h4><strong> ISBN:</strong> {{book.isbn}}</h4></p>

    {% if request.user.is_admin or request.user.is_superuser %}
    <br>
    <a class="btn btn-lg btn-info"  href="{% url 'library:book-update' book.id%}">Edit</a>
    {% endif %}

</div>
{% endblock content %}

library/templates/library/book_confirm_delete.html
{% extends 'library/base.html' %}
{% block content %}


<div >
    <a href="{% url 'library:book-list' %}">&#8592;Back</a>
</div>

<div >
    <form method = "POST">
        {%csrf_token%}
        <p>Are you sure you want to delete the book '{{book|title}}'?</p>
        <input class="button" type="submit" value="Submit">
        </form>
</div>



{% endblock content %}

library/templates/library/book_form.html
{% extends 'library/base.html' %}
{% block content %}




<div class="container" >
    <br>
    <a class="btn btn-sm btn-success" href="{% url 'library:book-list' %}">&#8592;Back</a>
    <form method="POST" enctype="multipart/form-data"action="">
    {%csrf_token%}

    <div class="mb-3 mt-3">
        <label >{{form.title.label}} </label>
        {{form.title}} 
    </div>
    <div class="mb-3 mt-3">
        <label >{{form.author.label}} </label>
        {{form.author}}  
    </div>
    <div class="mb-3 mt-3">
        <label >{{form.summary.label}} </label>
        {{form.summary}}
    </div>
    <div class="mb-3 mt-3">
        <label >{{form.isbn.label}} </label>
        {{form.isbn}} 
    </div>
    <div class="mb-3 mt-3">
          
    <label >{{form.genre.label}}</label>
    {{form.genre}} 
    </div>
    <div class="mb-3 mt-3">
        <label >{{form.language.label}} </label> 
    {{form.language}} 
    </div>
    <div class="mb-3 mt-3">
        <label >{{form.total_copies.label}}</label> 
        {{form.total_copies}}
    </div>
    <div class="mb-3 mt-3">
        <label >{{form.available_copies.label}}</label> 
        {{form.available_copies}}
    </div>
    <div class="mb-3 mt-3">
        <label >{{form.pic.label}}</label> 
        {{form.pic}} 
    </div>

    <label> <input class="btn btn-sm btn-success" type="submit" value="Submit"></label>
    
    </form>
</div>



{% endblock content %}

library/templates/library/book_list.html
{% extends "library/base.html" %} {% block content %}

<table class="table"  style="margin: auto;">
  <thead>
    <tr>
      <th scope="col">SN</th>
      <th scope="col">Book Title</th>
      <th scope="col">Author</th>
      <th scope="col">Available Copies</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  {% if books %}
  <tbody>
    {% for book in books %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{book.title}}</td>
      <td>{{book.author}}</td>
      <td>{{book.available_copies}}</td>
      <td>{% if request.user.is_admin or request.user.is_superuser %}<a class="btn btn-sm btn-success" href="{% url 'library:book-update' book.id%}">Update</a>  <a class="btn btn-sm btn-danger" href="{% url 'library:book-delete' book.id%}">Remove</a>  {% endif %} <a class="btn btn-sm btn-info" href="{% url 'library:book' book.id%}">Details</a> </td>
    </tr>

    {% endfor %}
  </tbody>
  {% else %}
  <tbody><tr><td colspan="6"> No Books in the Library.</td></tr></tbody>
  {% endif %}
</table>

{% endblock %}

library/templates/library/login.html
{% extends 'library/base.html' %}
{% block content %}


<div class="profile" >
    <br><br>
    <h2>Login Page</h2>
    <form action="{% url 'library:signin' %}" method="POST">{% csrf_token %}
        <div class="form-group form-focus">
            <label for="email" class="focus-label">Username</label>
            <input type="text" id="email" name="email" size="30">
            
        </div>
        <div class="form-group form-focus">
            <label for="password" class="focus-label">Password</label>
            <input type="password" id="password" name="password" size="30">
         
        </div>
     
        <div style="color:red;padding-bottom: 20px;">
            {{error}}
        </div>
        <button class="btn btn-primary btn-block btn-sm login-btn" type="submit">Login</button>
        <div class="login-or">
            <span class="or-line"></span>
            
        </div>
        <br>
        <p><strong>Fill in the form to register for the library: </strong><a class="btn btn-sm btn-success" href="{% url 'library:user-signup' %}">Register</a></p>
    </form>


</div>



{% endblock content %}

library/templates/library/main.html
{% extends 'library/base.html' %} {% block content %}


<div class="row" style="margin: auto;">

{% for book in books %}

<div class="card" style="width: 18rem">
  <span style="text-align: center;background-color: cadetblue;"></span>
  {% if book.pic %}
  <img src="{{book.pic.url}}" class="card-img-top" alt="" />
  {% else %}
  <img src="/static/avatar/open-book-clipart-03.png" class="card-img-top" alt="">
  {% endif %}
  <div class="card-body">
    <h5 class="card-title">{{book.title}}</h5>
    <p class="card-text">{{book.summary}}</p>
    <a href="{% url 'library:book' book.id %}" class="btn btn-primary"
      >View Details</a
    >
  </div>
</div>


{% endfor %}


</div>

{% endblock content %}

library/templates/library/register.html
{% extends 'library/base.html' %}
{% block content %}


<div class="profile" >

    <h2>Sign Page</h2>
    <form action="{% url 'library:user-signup' %}" method="POST">{% csrf_token %}
        <div class="form-group form-focus">
            <label class="focus-label">Email</label>
            <input type="email" name="email" size="30">
            
        </div>
        <div class="form-group form-focus">
            <label class="focus-label">Username</label>
            <input type="text" name="username" size="30">
          
        </div>
        <div class="form-group form-focus">
            <label class="focus-label">Password</label>
            <input type="password" name="password" size="30">
            
        </div>
        <div class="text-right">
            <a class="forgot-link" href="{% url 'library:signin' %}">Already have an account?</a>
        </div>
        <div style="color:red;padding-bottom: 20px;">
            {{error}}
        </div>
        <button class="btn btn-primary btn-block btn-lg login-btn" type="submit">Signup</button>
        <div class="login-or">
            <span class="or-line"></span>
        </div>
    </form>

</div>



{% endblock content %}

library/templates/partials/javascripts.html
{% load static %}
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{% static 'js/jquery-3.1.0.min.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>

library/templates/partials/stylesheets.html
{% load static %}
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href='http://fonts.googleapis.com/css?family=Raleway:400,600,800' rel='stylesheet' type='text/css'>